
const bcrypt = require('../node_modules/bcrypt');

exports.seed = async function (knex) {
  // Deletes ALL existing entries
  var numusers = 0
  var numtodos = 0
  // await knex('todo').del()
  await knex('user').del()
  var lastname = ['Smith',
    'Johnson',
    'Williams',
    'Jones',
    'Brown',
    'Davis',
    'Miller',
    'Wilson',
    'Moore',
    'Taylor',
    'Anderson',
    'Thomas',
    'Jackson',
    'White',
    'Harris',
    'Martin',
    'Thompson',
    'Garcia',
    'Martinez',
    'Robinson',
    'Clark',
    'Rodriguez',
    'Lewis',
    'Lee',
    'Walker',
    'Hall',
    'Allen',
    'Young',
    'Hernandez',
    'King',
    'Wright',
    'Lopez',
    'Hill',
    'Scott',
    'Green',
    'Adams',
    'Baker',
    'Gonzalez',
    'Nelson',
    'Carter',
    'Mitchell',
    'Perez',
    'Roberts',
    'Turner',
    'Phillips',
    'Campbell',
    'Parker',
    'Evans',
    'Edwards',
    'Collins',
    'Stewart',
    'Sanchez',
    'Morris',
    'Rogers',
    'Reed',
    'Cook',
    'Morgan',
    'Bell',
    'Murphy',
    'Bailey',
    'Rivera',
    'Cooper',
    'Richardson',
    'Cox',
    'Howard',
    'Ward',
    'Torres',
    'Peterson',
    'Gray',
    'Ramirez',
    'James',
    'Watson',
    'Brooks',
    'Kelly',
    'Sanders',
    'Price',
    'Bennett',
    'Wood',
    'Barnes',
    'Ross',
    'Henderson',
    'Coleman',
    'Jenkins',
    'Perry',
    'Powell',
    'Long',
    'Patterson',
    'Hughes',
    'Flores',
    'Washington',
    'Butler',
    'Simmons',
    'Foster',
    'Gonzales',
    'Bryant',
    'Alexander',
    'Russell',
    'Griffin',
    'Diaz',
    'Hayes',
  ];
  var firstname = [
    'Emma',
    'Olivia',
    'Ava',
    'Isabella',
    'Sophia',
    'Charlotte',
    'Mia',
    'Amelia',
    'Harper',
    'Evelyn',
    'Abigail',
    'Emily',
    'Elizabeth',
    'Mila',
    'Ella',
    'Avery',
    'Sofia',
    'Camila',
    'Aria',
    'Scarlett',
    'Victoria',
    'Madison',
    'Luna',
    'Grace',
    'Chloe',
    'Penelope',
    'Layla',
    'Riley',
    'Zoey',
    'Nora',
    'Lily',
    'Eleanor',
    'Hannah',
    'Lillian',
    'Addison',
    'Aubrey',
    'Ellie',
    'Stella',
    'Natalie',
    'Zoe',
    'Leah',
    'Hazel',
    'Violet',
    'Aurora',
    'Savannah',
    'Audrey',
    'Brooklyn',
    'Bella',
    'Claire',
    'Skylar',
    'Liam',
    'Noah',
    'William',
    'James',
    'Oliver',
    'Benjamin',
    'Elijah',
    'Lucas',
    'Mason',
    'Logan',
    'Alexander',
    'Ethan',
    'Jacob',
    'Michael',
    'Daniel',
    'Henry',
    'Jackson',
    'Sebastian',
    'Aiden',
    'Matthew',
    'Samuel',
    'David',
    'Joseph',
    'Carter',
    'Owen',
    'Wyatt',
    'John',
    'Jack',
    'Luke',
    'Jayden',
    'Dylan',
    'Grayson',
    'Levi',
    'Isaac',
    'Gabriel',
    'Julian',
    'Mateo',
    'Anthony',
    'Jaxon',
    'Lincoln',
    'Joshua',
    'Christopher',
    'Andrew',
    'Theodore',
    'Caleb',
    'Ryan',
    'Asher',
    'Nathan',
    'Thomas',
    'Leo'
  ];
  var todos = [
    'Go to the cinema',
    'Some',
    'Watch TV',
    'Spend time with family',
    'Go out with friends',
    'Surf the internet',
    'Play video games',
    'Play a musical instrument',
    'Listen to music',
    'Read',
    'Write',
    'Go to the park',
    'Go to cultural locations and events',
    'Go shopping',
    'Cook something',
    'Study something',
    'Art and crafts',
    'Gardening',
    'Exercise and play a sport',
  ];

  // for (var user in firstname) {
  //   console.log(await bcrypt.hash('password', 10));
  //   numusers++
  //   await knex('mykek.user').insert({
  //     givenname: firstname[user],
  //     surname: lastname[user],
  //     password: await bcrypt.hash('password', 10),
  //

  //   })
  // }

  var testusers = [
    { givenname: 'josiah', surname: 'schiesss', password: await bcrypt.hash('admin', 10), username: 'holo' }
  ]

  for (const user in testusers) {
    console.log(testusers[user]);
    await knex('mykek.user').insert(testusers[user])
  }

  var n = 3
  for (let i = 0; i < n; i++) {
    console.log(i);
    numtodos++
    // let temp = testusers[Math.floor(Math.random() * testusers.length)]
    // let cond = {
    //   givenname: temp,
    // }
    // console.log(JSON.stringify(cond));
    let owner = await knex('user').select('id').where({username: 'holo'});
    // console.log(owner[0].id);
    await knex('todo').insert({
      text: todos[Math.floor(Math.random() * todos.length)],
      start_date: new Date(),
      end_date: new Date(),
      status_id: Math.floor(Math.random() * 5) + 1,
      priority_id: Math.floor(Math.random() * 3) + 1,
      owner_id: owner[0].id
    })
  }


  // console.log(numusers+ ' Users created')
  // console.log(numtodos+ ' Todos created')
  // console.log(numtodos+numusers +' Total Entries Made')
  console.table({ 'Todos created': numtodos, 'Users created': numusers, 'Total Entries Made': numtodos + numusers })
};
